### ISSUE TITLE
ProxyServiceCaller call fails

### ISSUE THREAD

**Issue by joshjowen** [FlexBE/flexbe_behavior_engine#1]
When creating a simple state that calls the list_controllers service (and others) in Humble, I am getting a TypeError exception `"Invalid request type ListControllers_Request (vs. ListControllers) for topic /controller_manager/list_controllers"`. Here is the example state code:
```python
#!/usr/bin/env python
from flexbe_core import EventState, Logger
from flexbe_core.proxy import ProxyServiceCaller
from controller_manager_msgs.srv import ListControllers


class CheckControllerLoaded(EventState):
    '''
    Checks if a given controller is loaded.

    -- controller_name  str  name of controller to check.

    <= true     Controller is currently loaded.
    <= false    Controller is not loaded.
    '''

    def __init__(self, controller_name):
        super(CheckControllerLoaded, self).__init__(
            outcomes=['true', 'false'])
        ProxyServiceCaller._initialize(CheckControllerLoaded._node)

        self._controller_name = controller_name

        self._srv_topic = '/controller_manager/list_controllers'
        self._srv_result = None

        self._error = None

    def on_enter(self, userdata):
        # Try to call service to list controllers
        self._srv = ProxyServiceCaller(
            {self._srv_topic: ListControllers}, wait_duration=5.0)
        self._error = False
        try:
            request = ListControllers.Request()
            self._srv_result = self._srv.call(self._srv_topic, request)
        except Exception as e:
            Logger.logerr(f"Exception {str(e)}")
            self._error = True

    def execute(self, userdata):
        if (self._error) or (self._srv_result is None):
            return 'false'
        elif any(controller.name == self._controller_name for controller in self._srv_result.controller):
            return 'true'
        else:
            return 'false'

    def on_exit(self, userdata):
        pass

```
I was able to get it to work with these modifications universal-field-robots/flexbe_behavior_engine@b3228b2. I would have made a PR for it however I don't think this solution is in line with the intent of recent changes made in proxy_service_caller.py @ FlexBE/flexbe_behavior_engine@345e65c09bbfca6a0c74b0b5e833158ae9b4ca3b

**Comment by dcconner** [comment]
I believe the bug is real and your change is necessary, but not sufficient.   You are getting around the `if not isinstance` but will fail that that becomes true as in the case of reloaded behavior.  I don't have time to test and verify the fix until later this week.   If you want the fame that comes with an accepted PR we'll need to fix the `srv_type.__name__` lines as well, and come up with a simple test case.  Otherwise, I'll look into testing and fixing this weekend.

**Comment by dcconner** [comment]
@joshjowen I have issued PR #2 to fix this issue.  Thanks for catching this bug and reporting.   I have also done some clean up of the wait_duration and allow connection when the service is not present.   (I have requested review prior to merging as this includes some other changes.)  For testing, I created a simple behavior using the ROS Turtlesim demo.  You may check it out  [here](https://github.com/CNURobotics/flexbe_turtlesim_demo )  It might be worth looking at because I demonstrate setting up both blocking and non-blocking calls .  Your example above calls the proxy setup and makes service call in on_enter in a blocking manner.  Normally we want to avoid potential long duration calls in our states.   I appreciate any feedback on the new ROS 2 version of FlexBE
